=== morihofi/acmeserver/schema.settings.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "server": {
      "type": "object",
      "properties": {
        "dnsName": {
          "type": "string"
        },
        "ports": {
          "type": "object",
          "properties": {
            "https": {
              "type": "integer"
            },
            "http": {
              "type": "integer"
            }
          },
          "required": [
            "https",
            "http"
          ]
        },
        "loggingDirectory": {
          "type": "string"
        },
        "mozillaSslConfig": {
          "type": "object",
          "properties": {
            "enabled": {
              "type": "boolean"
            },
            "version": {
              "type": "string"
            },
            "configuration": {
              "type": "string"
            }
          },
          "required": [
            "enabled",
            "version",
            "configuration"
          ]
        },
        "sslServerConfig": {
          "type": "object",
          "properties": {
            "allowLegacyResumption": {
              "type": "boolean"
            },
            "enableSniCheck": {
              "type": "boolean"
            }
          },
          "required": [
            "allowLegacyResumption",
            "enableSniCheck"
          ]
        }
      },
      "required": [
        "dnsName",
        "ports",
        "loggingDirectory",
        "mozillaSslConfig",
        "sslServerConfig"
      ]
    },
    "keyStore": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "location": {
          "type": "string"
        },
        "libraryLocation": {
          "type": "string"
        }
      },
      "required": [
        "type",
        "password"
      ]
    },
    "database": {
      "type": "object",
      "properties": {
        "jdbcUrl": {
          "type": "string"
        },
        "user": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": [
        "jdbcUrl",
        "user",
        "password"
      ]
    },
    "network": {
      "type": "object",
      "properties": {
        "proxy": {
          "type": "object",
          "properties": {
            "enabled": {
              "type": "boolean"
            },
            "type": {
              "type": "string"
            },
            "host": {
              "type": "string"
            },
            "port": {
              "type": "integer"
            },
            "authentication": {
              "type": "object",
              "properties": {
                "enabled": {
                  "type": "boolean"
                },
                "username": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                }
              },
              "required": [
                "enabled",
                "username",
                "password"
              ]
            }
          },
          "required": [
            "enabled",
            "type",
            "host",
            "port",
            "authentication"
          ]
        },
        "dnsConfig": {
          "type": "object",
          "properties": {
            "dnsServers": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "dohEnabled": {
              "type": "boolean"
            },
            "dohEndpoint": {
              "type": "string"
            }
          },
          "required": [
            "dohEnabled",
            "dohEndpoint",
            "dnsServers"
          ]
        }
      },
      "required": [
        "proxy",
        "dnsConfig"
      ]
    },
    "certificateTransparency": {
      "type": "object",
      "properties": {
        "enabled": { "type": "boolean" },
        "logServer": { "type": "string" },
        "submitPreCertificate": { "type": "boolean" }
      },
      "required": [ "enabled", "logServer", "submitPreCertificate" ]
    }
  },
  "required": [
    "server",
    "keyStore",
    "database",
    "network"
  ]
}

=== morihofi/acmeserver/settings.sample.json
{
  "$schema": "schema.settings.json",
  "server": {
    "dnsName": "acme.example.com",
    "ports": {
      "https": 443,
      "http": 80
    },
    "loggingDirectory": "./serverdata/logs",
    "mozillaSslConfig": {
      "enabled": false,
      "version": "5.7",
      "configuration": "intermediate"
    },
    "sslServerConfig": {
      "allowLegacyResumption": false,
      "enableSniCheck": true
    }
  },
  "keyStore": {
    "type": "pkcs12",
    "password": "test",
    "location": "./serverdata/test.p12"
  },
  "database": {
    "jdbcUrl": "jdbc:h2:./serverdata/acme;DB_CLOSE_DELAY=-1",
    "user": "root",
    "password": ""
  },
  "network": {
    "proxy": {
      "enabled": false,
      "type": "socks",
      "host": "127.0.0.1",
      "port": 9050,
      "authentication": {
        "enabled": false,
        "username": "username",
        "password": "password"
      }
    },
    "dnsConfig": {
      "dnsServers": [
        "8.8.8.8",
        "8.8.4.4",
        "2001:4860:4860::8888",
        "2001:4860:4860::8844"
      ],
      "dohEnabled": false,
      "dohEndpoint": "https://cloudflare-dns.com/dns-query"
    }
  }
}
